version: '3'
services:
  pipbase:
    restart: always
    build: .
    shm_size: '2gb'
    container_name: 'pipbase'
    tty: true
    volumes:
     - ./:/root/src
     - ./usb/JAAD:/root/img
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]