version: '3'
services:
  pipbase:
    restart: always
    build: .
    shm_size: '2gb'
    container_name: 'pipbase'
    tty: true
    volumes:
     - ./:/workspaces/src
     - /media/naoki/2.5 HDD1 500GB2/JAAD:/workspaces/img
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]